name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache downloaded conda packages
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-v1-${{ hashFiles('conda.txt') }}
      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install python
          pip install dask setuptools wheel twine
          which python
          pip list
          conda list
      - name: Build and publish
        shell: bash -l {0}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
