---
name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: "Test (${{ matrix.os }}, python: ${{ matrix.python }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Cache downloaded conda packages
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-v1
      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install python=${{ matrix.python }}
          pip install -e ".[dev]"
          which python
          pip list
          conda list
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest --junitxml=junit/test-results.xml --cov-report=xml --cov uncertain_panda tests
      - name: Upload pytest test results
        uses: actions/upload-artifact@v1
        with:
          name: pytest-results
          path: junit/test-results.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
